シェルスクリプトスタイルのフォーマット統一
- shfmtを使用してフォーマットを統一
- インデントを2スペースに統一
- 条件文のスタイルを統一
- コメントの書式を統一
- 変数宣言のスタイルを統一

Co-Authored-By: Masato Sugiyama <public@smasato.net>

diff --git a/anyframe-functions/selectors/anyframe-selector-auto b/anyframe-functions/selectors/anyframe-selector-auto
--- a/anyframe-functions/selectors/anyframe-selector-auto
+++ b/anyframe-functions/selectors/anyframe-selector-auto
@@ -11,21 +11,21 @@ local selector_mode=''
 zstyle -s ":anyframe:selector:" use selector_mode || selector_mode=''
 
 if [[ $selector_mode != 'peco' ]] &&
-   [[ $selector_mode != 'percol' ]] &&
-   [[ $selector_mode != 'fzf-tmux' ]] &&
-   [[ $selector_mode != 'fzf' ]]; then
+  [[ $selector_mode != 'percol' ]] &&
+  [[ $selector_mode != 'fzf-tmux' ]] &&
+  [[ $selector_mode != 'fzf' ]]; then
   # selector isn't specified
   if which peco > /dev/null 2>&1; then
-  selector_mode='peco'
+    selector_mode='peco'
   elif which percol > /dev/null 2>&1; then
-  selector_mode='percol'
+    selector_mode='percol'
   elif which fzf-tmux > /dev/null 2>&1; then
-  selector_mode='fzf-tmux'
+    selector_mode='fzf-tmux'
   elif which fzf > /dev/null 2>&1; then
-  selector_mode='fzf'
+    selector_mode='fzf'
   else
-  echo "anyframe: not found any of peco, percol, or fzf" 1>&2
-  return 1
+    echo "anyframe: not found any of peco, percol, or fzf" 1>&2
+    return 1
   fi
 fi
 
diff --git a/anyframe-functions/sources/anyframe-source-git-branch b/anyframe-functions/sources/anyframe-source-git-branch
--- a/anyframe-functions/sources/anyframe-source-git-branch
+++ b/anyframe-functions/sources/anyframe-source-git-branch
@@ -11,36 +11,36 @@ local git_option
 git_option=("--list" "-v")
 while getopts ':inar' option; do
   case $option in
-  i)
-  include_current_branch="1"
-  ;;
-  n)
-  include_current_branch="0"
-  ;;
-  a)
-  git_option+=("-a")
-  ;;
-  r)
-  git_option+=("-r")
-  ;;
-  *)
-  echo "$0: invalid option -- $OPTARG" 1>&2
-  return 1
-  ;;
+    i)
+      include_current_branch="1"
+      ;;
+    n)
+      include_current_branch="0"
+      ;;
+    a)
+      git_option+=("-a")
+      ;;
+    r)
+      git_option+=("-r")
+      ;;
+    *)
+      echo "$0: invalid option -- $OPTARG" 1>&2
+      return 1
+      ;;
   esac
 done
 shift $(expr $OPTIND - 1)
 
-git branch $git_option \
-| {
-  if [[ "$include_current_branch" == "1" ]]; then
-  sed 's/^\*//'
-  else
-  # remove current branch name
-  grep -v '^\*'
-  fi
-} \
-| sed 's/^  *//'
+git branch $git_option |
+  {
+    if [[ "$include_current_branch" == "1" ]]; then
+      sed 's/^\*//'
+    else
+      # remove current branch name
+      grep -v '^\*'
+    fi
+  } |
+  sed 's/^  *//'
 
 # Local Variables:
 # mode: Shell-Script
