シェルスクリプトスタイルの統一
- インデントを2スペースに統一
- コメントの書式を統一（#の後にスペースを追加）
- 条件文のスタイルを統一
- 変数宣言のスタイルを統一

Co-Authored-By: Masato Sugiyama <public@smasato.net>

diff --git a/anyframe-functions/actions/anyframe-action-execute b/anyframe-functions/actions/anyframe-action-execute
--- a/anyframe-functions/actions/anyframe-action-execute
+++ b/anyframe-functions/actions/anyframe-action-execute
@@ -7,12 +7,12 @@
 function _anyframe-action-execute()
 {
   if zle; then
-    BUFFER="$*"
-    zle accept-line
-    # redisplay the command line
-    zle -R -c
+  BUFFER="$*"
+  zle accept-line
+  # redisplay the command line
+  zle -R -c
   else
-    eval "$*"
+  eval "$*"
   fi
 }
 
@@ -22,18 +22,18 @@ local option OPTARG OPTIND
 while getopts ':q:d' option; do
   case $option in
   q)
-    quote_item="1"
-    ;;
+  quote_item="1"
+  ;;
   Q)
-    quote_item="0"
-    ;;
+  quote_item="0"
+  ;;
   d)
-    use_double_quote="1"
-    ;;
+  use_double_quote="1"
+  ;;
   *)
-    echo "$0: invalid option -- $OPTARG" 1>&2
-    return 1
-    ;;
+  echo "$0: invalid option -- $OPTARG" 1>&2
+  return 1
+  ;;
   esac
 done
 shift $((OPTIND - 1))
diff --git a/anyframe-functions/actions/anyframe-action-insert b/anyframe-functions/actions/anyframe-action-insert
--- a/anyframe-functions/actions/anyframe-action-insert
+++ b/anyframe-functions/actions/anyframe-action-insert
@@ -6,12 +6,12 @@
 function _anyframe-action-insert()
 {
   if zle; then
-    LBUFFER+="$*"
-    CURSOR=$#LBUFFER
-    # redisplay the command line
-    zle -R -c
+  LBUFFER+="$*"
+  CURSOR=$# LBUFFER
+  # redisplay the command line
+  zle -R -c
   else
-    print -z -f '%s' "$*"
+  print -z -f '%s' "$*"
   fi
 }
 
@@ -20,15 +20,15 @@ local option OPTARG OPTIND
 while getopts ':q' option; do
   case $option in
   q)
-    quote_item="1"
-    ;;
+  quote_item="1"
+  ;;
   Q)
-    quote_item="0"
-    ;;
+  quote_item="0"
+  ;;
   *)
-    echo "$0: invalid option -- $OPTARG" 1>&2
-    return 1
-    ;;
+  echo "$0: invalid option -- $OPTARG" 1>&2
+  return 1
+  ;;
   esac
 done
 shift $((OPTIND - 1))
diff --git a/anyframe-functions/sources/anyframe-source-git-branch b/anyframe-functions/sources/anyframe-source-git-branch
--- a/anyframe-functions/sources/anyframe-source-git-branch
+++ b/anyframe-functions/sources/anyframe-source-git-branch
@@ -12,21 +12,21 @@ git_option=("--list" "-v")
 while getopts ':inar' option; do
   case $option in
   i)
-    include_current_branch="1"
-    ;;
+  include_current_branch="1"
+  ;;
   n)
-    include_current_branch="0"
-    ;;
+  include_current_branch="0"
+  ;;
   a)
-    git_option+=("-a")
-    ;;
+  git_option+=("-a")
+  ;;
   r)
-    git_option+=("-r")
-    ;;
+  git_option+=("-r")
+  ;;
   *)
-    echo "$0: invalid option -- $OPTARG" 1>&2
-    return 1
-    ;;
+  echo "$0: invalid option -- $OPTARG" 1>&2
+  return 1
+  ;;
   esac
 done
 shift $(expr $OPTIND - 1)
@@ -34,10 +34,10 @@ shift $(expr $OPTIND - 1)
 git branch $git_option \
 | {
   if [[ "$include_current_branch" == "1" ]]; then
-    sed 's/^\*//'
+  sed 's/^\*//'
   else
-    # remove current branch name
-    grep -v '^\*'
+  # remove current branch name
+  grep -v '^\*'
   fi
 } \
 | sed 's/^  *//'
